/**
 * status-history.ts — **one** shape definition for a document's Status History record.
 *
 * Why this module exists (`TASK-20260911080931450`): the writer and the reader of the
 * Status History were never looked at side by side, and the CLI ended up writing a format
 * the CLI itself could not read — `move` appended a **bare row** (no heading, no table
 * header) to any card that did not have a `## Status History` section, while `probe`
 * required that heading. Every card not generated by `template.ts` (hand-written, arena
 * follow-ups, ingested) hit the bare-row branch on its first state transition. The rule
 * that closes it is `ADR-20260910152957509`'s general clause: **the writer's grammar is the
 * reader's grammar**.
 *
 * The single rule, in one sentence (the plan-gate's round-3 correction — the property had
 * been pinned on the *heading*, while it is a property of the *record*):
 *
 *   **The canonical table is the header-bearing table. Every other vocabulary row is a
 *   to-be-folded row.**
 *
 * `locate` / `read` / `parse` / `append` are the only shape definition; `probe.ts` and
 * `flow.ts` build on it, and `move.ts` no longer owns a private copy.
 *
 * **Fences — one map, every scan.** A fenced code block is documentation, not a record, so
 * `locate`, the canonical-table scan **and** the folded-row scan all read the same fence
 * map. Hardening one scan while leaving its twin is precisely how the writer and the reader
 * drifted apart (plan-gate round 2, N1: the writer's locator became fence-aware while the
 * reader's recogniser did not, so on a fenced card the writer reported success while the
 * reader could see nothing). Measured 2026-09-11: 0 of 542 cards hold a vocabulary row
 * inside a fence — the branch is closed by AC7, not by corpus evidence.
 */

export type DocKind = 'task' | 'adr' | 'epic';

/** A structured Status History row. `note` is **everything after the second cell**,
 *  joined with ` | ` — never `cells[2]`, or a row whose note itself contains a `|`
 *  (measured: 3 cards) gets truncated the moment it is rewritten. */
export interface StatusRow {
  /** First cell — the status word. May carry a revision marker: `backlog (revised)`. */
  status: string;
  /** Second cell — the Date column, UTC convention (`YYYY-MM-DD`). */
  date: string;
  /** Everything from the third cell on, joined with ` | `. May contain ` | `. */
  note: string;
}

export interface LocatedHeading {
  /** 0-based line index into `content.split('\n')`. */
  line: number;
  text: string;
}

/** The status vocabulary per document kind — the discriminator that separates a
 *  *record* row from any other table in the file (a `## 进度记录` RED/GREEN table, a
 *  `| ADR | 标题 | 状态 |` index, …). */
export const STATUS_VOCABULARY: Record<DocKind, readonly string[]> = {
  task: ['backlog', 'in-progress', 'review', 'completed', 'suspended', 'terminated', 'archived'],
  adr: ['proposed', 'accepted', 'rejected', 'superseded'],
  epic: ['active', 'done', 'suspended', 'archived'],
};

/** The status a document of this kind is created in (`template.ts`). A Status History
 *  table that is being *written from scratch* states its own origin; one that already
 *  exists is left alone. */
export const INITIAL_STATUS: Record<DocKind, string> = {
  task: 'backlog',
  adr: 'proposed',
  epic: 'active',
};

/** The block shape, verbatim from `template.ts` / `templates/epic.md`. */
export const STATUS_HISTORY_HEADING = '## Status History';
export const STATUS_HISTORY_COMMENT =
  '<!-- machine-parseable table: directory = current status, last row = latest record -->';
export const TABLE_HEADER = '| Status | Date | Note |';
export const TABLE_SEPARATOR = '|--------|------|------|';

/** `## Status History` — the only heading this module recognises. */
const HEADING_RE = /^##\s+Status\s+History\s*$/i;

/** Legacy `## Status` single-line form. **Verbatim** from the pre-existing reader
 *  (`probe.ts`), including the `\s*` that skips blank lines between the heading and the
 *  value: `probe.test.ts:194` pins `## Status\n\nbacklog\n`, so "the next line" is wrong.
 *  Never converted — an ungated conversion would give `ADR-20260509155630` (which carries
 *  both `## Status` and `## Status History`) two headings and freeze it. */
const LEGACY_STATUS_RE = /##\s+Status\s*\n\s*(\S[^\n]*)/i;

/** One row of the canonical table, with its position. */
interface TableRow {
  line: number;
  cells: string[];
}

interface CanonicalTable {
  headerLine: number;
  /** Last line of the table block — where an appended row goes. */
  lastRow: number;
  rows: TableRow[];
}

// ---------------------------------------------------------------------------
// Line-level primitives
// ---------------------------------------------------------------------------

/** Mark which lines sit inside a fenced code block (the delimiter lines count as fenced). */
function fenceMap(lines: string[]): boolean[] {
  const fenced = new Array<boolean>(lines.length).fill(false);
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    if (/^\s*(```|~~~)/.test(lines[i])) {
      inFence = !inFence;
      fenced[i] = true;
      continue;
    }
    fenced[i] = inFence;
  }
  return fenced;
}

function isTableLine(line: string): boolean {
  return line.trim().startsWith('|');
}

function isSeparatorRow(line: string): boolean {
  return /^\|[-\s|]+\|$/.test(line.trim());
}

/** Split a table line into trimmed, non-empty cells. */
function splitCells(line: string): string[] {
  return line.trim().split('|').map(c => c.trim()).filter(c => c.length > 0);
}

/** The status word of a row: the first whitespace token of the first cell, lowercased.
 *  `backlog (revised)` → `backlog`; `RED` → `red` (not a vocabulary word — AC7's negative). */
export function statusToken(status: string): string {
  return status.trim().split(/\s+/)[0]?.toLowerCase() ?? '';
}

function rowFromCells(cells: string[]): StatusRow {
  return {
    status: cells[0] ?? '',
    date: cells[1] ?? '',
    note: cells.slice(2).join(' | '),
  };
}

/** Serialise a row back into the canonical shape. Used for the *new* row and for folded
 *  rows, which are moved into the canonical table. */
export function formatRow(status: string, date: string, note: string): string {
  return `| ${status} | ${date} | ${note} |`;
}

/** `TASK-20260909010058114` → the 17-digit timestamp it carries. */
const ID_TIMESTAMP_RE = /(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\d{3})/;

/** The UTC calendar date of a document ID's own timestamp, or null when the ID carries no
 *  timestamp (`TASK-TEST-001`, a hand-written id).
 *
 *  IDs are minted from **local** wall-clock time (`generateTimestampId`), while the Date
 *  column is written in UTC (`toISOString().split('T')[0]`), so the ID's reading must be
 *  normalised to the column's convention: read directly, a naive local-date disagrees with
 *  the corpus convention for 73 of 507 cards (~14%, measured 2026-09-11). The value is
 *  computed in the ambient zone on purpose — that is what turns a local reading into its
 *  UTC date, and it is why this must not be a string slice. */
function utcDateFromId(id: string | undefined): string | null {
  const m = id?.match(ID_TIMESTAMP_RE);
  if (!m) return null;
  const d = new Date(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6], +m[7]);
  if (isNaN(d.getTime())) return null;
  return d.toISOString().split('T')[0];
}

// ---------------------------------------------------------------------------
// locate — the ONLY heading finder
// ---------------------------------------------------------------------------

/**
 * Find `## Status History` headings, line by line, fence-aware, anchored on `trim()`.
 *
 * Returns every candidate with its 0-based line number (0, 1 or — in the shapes this repo
 * actually contains — more). No caller may re-implement this search: a second, slightly
 * different copy of it is exactly how the writer and the reader drifted apart.
 */
export function locate(content: string): LocatedHeading[] {
  const lines = content.split('\n');
  const fenced = fenceMap(lines);
  const found: LocatedHeading[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (fenced[i]) continue;
    const text = lines[i].trim();
    if (HEADING_RE.test(text)) found.push({ line: i, text });
  }
  return found;
}

// ---------------------------------------------------------------------------
// read — the canonical table only
// ---------------------------------------------------------------------------

/** The canonical table = the header-bearing `| Status | Date | … |` table. */
function findCanonicalTable(lines: string[], fenced: boolean[]): CanonicalTable | null {
  for (let i = 0; i < lines.length; i++) {
    if (fenced[i] || !isTableLine(lines[i]) || isSeparatorRow(lines[i])) continue;
    const cells = splitCells(lines[i]);
    if (cells.length < 2) continue;
    if (cells[0].toLowerCase() !== 'status') continue;
    if (!cells.slice(1).some(c => /^date$/i.test(c))) continue;

    const rows: TableRow[] = [];
    let lastRow = i;
    for (let j = i + 1; j < lines.length; j++) {
      if (!isTableLine(lines[j])) break;
      lastRow = j;
      if (isSeparatorRow(lines[j])) continue;
      rows.push({ line: j, cells: splitCells(lines[j]) });
    }
    return { headerLine: i, lastRow, rows };
  }
  return null;
}

/**
 * Structured rows, read from **the canonical table only**.
 *
 * Deliberately *not* a repair path: a row that is not part of the canonical table is not
 * read here — it is a folded row, and `append` is what moves it in.
 */
export function read(content: string): StatusRow[] {
  const lines = content.split('\n');
  const fenced = fenceMap(lines);
  const table = findCanonicalTable(lines, fenced);
  return table ? table.rows.map(r => rowFromCells(r.cells)) : [];
}

// ---------------------------------------------------------------------------
// parse — the { lines, hasSection, singleStatus } triple probe/flow consume
// ---------------------------------------------------------------------------

export interface ParsedStatusHistory {
  lines: string[];
  hasSection: boolean;
  singleStatus: string | null;
}

/**
 * The triple `probe.ts`'s `extractStatusHistory` used to compute privately, derived from
 * `read` so that the reader and the writer cannot disagree about which rows exist.
 */
export function parse(content: string): ParsedStatusHistory {
  if (locate(content).length > 0) {
    return { lines: read(content).map(r => r.status), hasSection: true, singleStatus: null };
  }

  const rows = read(content);
  if (rows.length > 0) {
    // A header-bearing table without the heading: the record exists, so the section does.
    return { lines: rows.map(r => r.status), hasSection: true, singleStatus: null };
  }

  const legacy = content.match(LEGACY_STATUS_RE);
  if (legacy) {
    const status = legacy[1].trim();
    return { lines: [status], hasSection: true, singleStatus: status };
  }

  return { lines: [], hasSection: false, singleStatus: null };
}

// ---------------------------------------------------------------------------
// append — never refuses, never fabricates
// ---------------------------------------------------------------------------

/** A vocabulary row that is not part of the canonical table. */
interface FoldedRow {
  line: number;
  row: StatusRow;
}

function findFoldedRows(
  lines: string[],
  fenced: boolean[],
  kind: DocKind,
  table: CanonicalTable | null,
): FoldedRow[] {
  const vocabulary = STATUS_VOCABULARY[kind];
  const canonicalLines = new Set<number>();
  if (table) {
    for (let i = table.headerLine; i <= table.lastRow; i++) canonicalLines.add(i);
  }

  const folded: FoldedRow[] = [];
  for (let i = 0; i < lines.length; i++) {
    // Fenced lines are documentation, never rows of the record — the same fence map that
    // `locate` and the canonical-table scan use. Hardening one scan while leaving its twin
    // is how the writer and the reader drifted apart in the first place (round 2, N1), so
    // there is exactly one map and every scan reads it.
    if (fenced[i] || canonicalLines.has(i)) continue;
    if (!isTableLine(lines[i]) || isSeparatorRow(lines[i])) continue;
    const cells = splitCells(lines[i]);
    if (cells.length < 2) continue;
    if (!vocabulary.includes(statusToken(cells[0]))) continue;
    folded.push({ line: i, row: rowFromCells(cells) });
  }
  return folded;
}

/**
 * Append a status transition to a document's Status History.
 *
 * **Never refuses, never fabricates.** It writes exactly one new row (the transition) plus,
 * when it is writing a table from scratch, the kind's *origin* row — and it moves rows the
 * reader could not see into the table the reader reads.
 *
 * - no section at all        → the full block (heading + comment + header + separator) + rows
 * - canonical table present  → rows appended at the end of that table
 * - section without a table  → header + separator + rows, at the section head
 * - folded rows present      → moved, order-preserving, to the end of the canonical table
 *
 * The origin row is **only reachable from the two paths that write a table from scratch**
 * (no canonical table) — the canonical-table path returns before the row list is built, so
 * the `!table` term below is belt-and-braces, not the mechanism. It is also skipped when
 * the folded rows already carry that status, and when the transition being recorded IS that
 * status (otherwise the same fact would be written twice). It is never prepended to an
 * existing canonical table: 20 of the 542 cards scanned on 2026-09-11 (10 task + 9 ADR +
 * 1 epic) have a canonical table that never started at the initial status, and inventing an
 * origin for them would be fabrication.
 *
 * The origin row is a **reconstruction** — the card already exists, so the writer is stating
 * where its record began, not recording an event that just happened. Its date therefore
 * comes from the document ID's own timestamp (normalised to the Date column's UTC
 * convention), never from `date` (the transition date), and its note says so. Dating it by
 * the transition would both falsify the origin and, because `flow` reads row 0, silently
 * reset the card's age to zero the moment it is repaired.
 *
 * `date` is the caller's and must follow the Date column's UTC convention —
 * `new Date().toISOString().split('T')[0]`.
 */
export function append(
  content: string,
  kind: DocKind,
  status: string,
  date: string,
  note: string,
  sourceId?: string,
): string {
  const lines = content.split('\n');
  const fenced = fenceMap(lines);
  const table = findCanonicalTable(lines, fenced);
  const folded = findFoldedRows(lines, fenced, kind, table);

  const newRow = formatRow(status, date, note);
  const foldedLines = folded.map(f => formatRow(f.row.status, f.row.date, f.row.note));
  const idDate = utcDateFromId(sourceId);
  const originRow = formatRow(
    INITIAL_STATUS[kind],
    idDate ?? date,
    idDate ? 'Created (reconstructed from card ID)' : 'Created (reconstructed; no card ID)',
  );
  const includeOrigin =
    !table &&
    statusToken(status) !== INITIAL_STATUS[kind] &&
    !folded.some(f => statusToken(f.row.status) === INITIAL_STATUS[kind]);

  const removed = new Set(folded.map(f => f.line));

  // ── canonical table present: move the folded rows to its end, then append ──
  if (table) {
    const out: string[] = [];
    let insertAt = -1;
    for (let i = 0; i < lines.length; i++) {
      if (removed.has(i)) continue;
      out.push(lines[i]);
      if (i === table.lastRow) insertAt = out.length;
    }
    out.splice(insertAt < 0 ? out.length : insertAt, 0, ...foldedLines, newRow);
    return out.join('\n');
  }

  const rows = [...(includeOrigin ? [originRow] : []), ...foldedLines, newRow];

  // ── section present without a table: write the header there ──
  const headings = locate(content);
  if (headings.length > 0) {
    let insertAfter = headings[0].line;
    // The block comment (or any comment) that directly follows the heading belongs to it.
    if (lines[insertAfter + 1] !== undefined && /^\s*<!--/.test(lines[insertAfter + 1])) {
      insertAfter += 1;
    }

    let removedBefore = 0;
    for (const f of folded) if (f.line <= insertAfter) removedBefore += 1;

    const out: string[] = [];
    for (let i = 0; i < lines.length; i++) {
      if (removed.has(i)) continue;
      out.push(lines[i]);
    }

    const at = Math.min(insertAfter + 1 - removedBefore, out.length);
    const block: string[] = [];
    if (out[at] !== undefined && out[at].trim() !== '') block.push('');
    block.push(TABLE_HEADER, TABLE_SEPARATOR, ...rows);
    if (out[at] !== undefined && out[at].trim() !== '') block.push('');
    out.splice(at, 0, ...block);
    return out.join('\n');
  }

  // ── no section at all: write the full block, at the end of the document ──
  const kept: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (removed.has(i)) continue;
    kept.push(lines[i]);
  }
  const body = kept.join('\n').replace(/\n+$/, '');
  const block = [
    STATUS_HISTORY_HEADING,
    STATUS_HISTORY_COMMENT,
    '',
    TABLE_HEADER,
    TABLE_SEPARATOR,
    ...rows,
  ].join('\n');
  return body.length > 0 ? `${body}\n\n${block}\n` : `${block}\n`;
}
