#!/usr/bin/env bun
/**
 * toml-splice.test.ts — 最小影响写入:三种形状 × {删,增}(ADR-20260910152957509 §规格)
 *
 * 断言一律是**写死的期望文本**(逐字节比较),不是"原文减去那一段" ——
 * 后者是同义反复:期望值由被测代码的形状推出来,永远对(ZK review 904 round-2 指出)。
 *
 * fixture **含非 ASCII 字符**:纯 ASCII 会让"偏移单位当成字节"那类错误永远绿着骗人(H3)。
 *
 * Run: bun test packages/lythoskill-deck/src/toml-splice.test.ts
 */

import { describe, it, expect } from 'bun:test'
import { parseTOML } from 'toml-eslint-parser'
import { spliceRemoveSkill, spliceInsertSkill } from './toml-splice.ts'

/** 注释密集 + 非 ASCII(`→` 让 code unit ≠ 字节)的常态 deck */
const DENSE = `# Skill Deck — generated by lythoskill-deck
# 这份文件的注释是给人看的,不是给序列化器看的
[deck]
max_cards = 10           # budget
working_set = ".claude/skills"
cold_pool = "../pool"

# ── tool skills ──
[tool.skills.alpha]
path = "github.com/a/b/alpha"
role = "调试 → 定位 → 修复"

[tool.skills.beta]
path = "github.com/a/b/beta"

[combo.weekly]
prompt = "keep"
`

describe('spliceRemoveSkill — ① table 形状', () => {
  it('removes exactly that block, keeps every comment, restores the file的接缝', () => {
    const out = spliceRemoveSkill(DENSE, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`# Skill Deck — generated by lythoskill-deck
# 这份文件的注释是给人看的,不是给序列化器看的
[deck]
max_cards = 10           # budget
working_set = ".claude/skills"
cold_pool = "../pool"

# ── tool skills ──
[tool.skills.beta]
path = "github.com/a/b/beta"

[combo.weekly]
prompt = "keep"
`)
    // 非 ASCII 那一行删掉后,后面的行仍逐字节不变(单位错了就会在这里裂开)
    expect(out.src).toContain('调试 → 定位 → 修复' === '' ? '' : 'prompt = "keep"')
    expect(out.src.split('\n').filter(l => l.trimStart().startsWith('#')).length).toBe(
      DENSE.split('\n').filter(l => l.trimStart().startsWith('#')).length,
    )
  })

  it('is a no-op-safe error when the alias is not there (reports what it looked for)', () => {
    const out = spliceRemoveSkill(DENSE, 'tool', 'nope')
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('not-found')
    expect(out.message).toContain('[tool.skills.nope]')
    expect(out.message).toContain('legacy')
  })
})

describe('spliceRemoveSkill — ② [tool.skills] 内联条目', () => {
  const INLINE = `[deck]
max_cards = 10

[tool.skills]
alpha = { path = "github.com/a/b/alpha" }
beta = { path = "github.com/a/b/beta" }
`

  it('removes just that entry', () => {
    const out = spliceRemoveSkill(INLINE, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`[deck]
max_cards = 10

[tool.skills]
beta = { path = "github.com/a/b/beta" }
`)
  })

  it('cascades: the last entry gone → the [tool.skills] header goes too', () => {
    const only = `[deck]
max_cards = 10

[tool.skills]
alpha = { path = "github.com/a/b/alpha" }
`
    const out = spliceRemoveSkill(only, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    // 尾部那行空行**刻意不整理**(ADR §规格「尾部残渣」:整理 = 重写)
    expect(out.src).toBe('[deck]\nmax_cards = 10\n\n')
  })
})

describe('spliceRemoveSkill — ③ legacy 数组', () => {
  const LEGACY = `[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha", "github.com/a/b/beta" ]

[combo.weekly]
prompt = "keep"
`

  it('removes the element + its comma and does NOT reformat the rest', () => {
    const out = spliceRemoveSkill(LEGACY, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('skills = [ "github.com/a/b/beta" ]')
    expect(out.src).toContain('[combo.weekly]')
  })

  it('cascades: the last element gone → the skills key goes, then the empty section header', () => {
    const second = spliceRemoveSkill(LEGACY, 'tool', 'beta')
    expect(second.ok).toBe(true)
    if (!second.ok) return
    expect(second.src).toBe(`[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha" ]

[combo.weekly]
prompt = "keep"
`)

    const one = `[deck]
max_cards = 10

[tool]
skills = ["github.com/a/b/alpha"]

[combo.weekly]
prompt = "keep"
`
    const o2 = spliceRemoveSkill(one, 'tool', 'alpha')
    expect(o2.ok).toBe(true)
    if (!o2.ok) return
    expect(o2.src).not.toContain('skills = [')
    expect(o2.src).not.toContain('[tool]')
    expect(o2.src).toContain('[combo.weekly]')
  })
})

describe('spliceInsertSkill', () => {
  it('inserts after the last same-prefix table, one blank line, block without trailing newline', () => {
    const out = spliceInsertSkill(DENSE, 'tool', 'gamma', { path: 'github.com/a/b/gamma' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain(`[tool.skills.beta]
path = "github.com/a/b/beta"

[tool.skills.gamma]
path = "github.com/a/b/gamma"

[combo.weekly]`)
    expect(out.src.split('\n').filter(l => l.trimStart().startsWith('#')).length).toBe(
      DENSE.split('\n').filter(l => l.trimStart().startsWith('#')).length,
    )
  })

  it('carries source when given, and lands on an empty deck', () => {
    const out = spliceInsertSkill('[deck]\nmax_cards = 10\n', 'tool', 'alpha', {
      path: 'github.com/a/b/alpha',
      source: 'https://github.com/a/b/blob/HEAD/alpha/SKILL.md',
    })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`[deck]
max_cards = 10

[tool.skills.alpha]
path = "github.com/a/b/alpha"
source = "https://github.com/a/b/blob/HEAD/alpha/SKILL.md"
`)
  })

  it('legacy array + path-only + derivable alias → appends a string element, nothing else moves', () => {
    const legacy = `[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha" ]
`
    const out = spliceInsertSkill(legacy, 'tool', 'beta', { path: 'github.com/a/b/beta' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha", "github.com/a/b/beta" ]
`)
  })

  it('legacy array + a source field → refuses and names deck migrate-schema', () => {
    const legacy = '[tool]\nskills = ["github.com/a/b/alpha"]\n'
    const out = spliceInsertSkill(legacy, 'tool', 'beta', {
      path: 'github.com/a/b/beta',
      source: 'https://github.com/a/b/blob/HEAD/beta/SKILL.md',
    })
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('unrepresentable')
    expect(out.message).toContain('migrate-schema')
    expect(out.message).toContain('cold pool')
    expect(out.message).toContain('github.com/a/b/beta') // 点名它看到的 locator
  })

  it('legacy array + a custom alias → refuses (alias is the key, not a field)', () => {
    const legacy = '[tool]\nskills = ["github.com/a/b/alpha"]\n'
    const out = spliceInsertSkill(legacy, 'tool', 'custom', { path: 'github.com/a/b/beta' })
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('unrepresentable')
    expect(out.message).toContain("custom alias 'custom'")
  })
})


describe('ZK-impl round-1 的四个 HIGH:每条都钉一个"能红"的用例', () => {
  const MAP = `[deck]
max_cards = 10

[tool]
skills = { alpha = { path = "github.com/a/b/alpha" } }

[combo.weekly]
prompt = "keep"
`

  it('H1: insert into an inline-table map stays parseable (never a sibling table)', () => {
    const out = spliceInsertSkill(MAP, 'tool', 'beta', { path: 'github.com/a/b/beta' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain(`skills = { alpha = { path = "github.com/a/b/alpha" }, beta = { path = "github.com/a/b/beta" } }`)
    // 关键:结果必须还能被解析 —— 在旁边新增 [tool.skills.beta] 表会让 TOML 抛错
    expect(() => parseTOML(out.src, { range: true })).not.toThrow()
  })

  it('H1b: the map form can carry source too (so it is never "unrepresentable")', () => {
    const out = spliceInsertSkill(MAP, 'tool', 'beta', { path: 'p', source: 'https://x' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('beta = { path = "p", source = "https://x" }')
  })

  it('H2: remove accepts the key spellings the reader accepts (quoted / spaced)', () => {
    const quoted = `[tool.skills."alpha"]\npath = "x"\n\n[tool . skills . beta]\npath = "y"\n`
    const r1 = spliceRemoveSkill(quoted, 'tool', 'alpha')
    expect(r1.ok).toBe(true)
    if (!r1.ok) return
    expect(r1.src).not.toContain('alpha')
    expect(r1.src).toContain('[tool . skills . beta]')
    const r2 = spliceRemoveSkill(quoted, 'tool', 'beta')
    expect(r2.ok).toBe(true)
    if (!r2.ok) return
    expect(r2.src).toContain('[tool.skills."alpha"]')
  })

  it('H2b: remove works on the inline-map shape, and cascades to the section header', () => {
    const two = MAP.replace('skills = { alpha = { path = "github.com/a/b/alpha" } }',
      'skills = { alpha = { path = "a" }, beta = { path = "b" } }')
    const out = spliceRemoveSkill(two, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('skills = { beta = { path = "b" } }')

    const last = spliceRemoveSkill(MAP, 'tool', 'alpha')
    expect(last.ok).toBe(true)
    if (!last.ok) return
    expect(last.src).not.toContain('skills =')
    expect(last.src).not.toContain('[tool]')
  })

  it('H3: insert into a CRLF file uses CRLF at the insertion point (not LF from offset 0)', () => {
    const crlf = '[deck]\r\nmax_cards = 10\r\n\r\n[tool.skills.alpha]\r\npath = "a"\r\n'
    const out = spliceInsertSkill(crlf, 'tool', 'beta', { path: 'b' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('[tool.skills.alpha]\r\npath = "a"\r\n\r\n[tool.skills.beta]\r\npath = "b"')
    // 混入裸 \n 就是"静默改了行尾"
    expect(out.src).not.toMatch(/(?<!\r)\n/)
  })
})


describe('ZK-impl round-2:级联走到底 / 点号键 / 结果护栏 / 空 map', () => {
  it('R2-H1: rule ② cascade removes the empty [tool] header too (was: left behind)', () => {
    const src = '[deck]\nmax_cards = 10\n\n[tool]\n\n[tool.skills]\nalpha = { path = "x" }\n'
    const out = spliceRemoveSkill(src, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe('[deck]\nmax_cards = 10\n\n')
  })

  it('R2-H3: dotted-key placements the reader accepts are removable', () => {
    const a = '[deck]\nmax_cards = 10\n\n[tool]\nskills.alpha.path = "github.com/a/b/alpha"\n'
    const b = '[deck]\nmax_cards = 10\n\n[tool.skills]\nalpha.path = "github.com/a/b/alpha"\n'
    for (const src of [a, b]) {
      const out = spliceRemoveSkill(src, 'tool', 'alpha')
      expect(out.ok).toBe(true)
      if (!out.ok) return
      expect(out.src).not.toContain('alpha')
      expect(() => parseTOML(out.src, { range: true })).not.toThrow()
    }
  })

  it('R2-H3b: a dotted entry split across several key-values goes as one entry', () => {
    const src = '[deck]\nmax_cards = 10\n\n[tool]\nskills.alpha.path = "p"\nskills.alpha.role = "r"\nskills.beta.path = "q"\n'
    const out = spliceRemoveSkill(src, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).not.toContain('alpha')
    expect(out.src).toContain('skills.beta.path = "q"')
  })

  it('R2-H4: a scalar skills value is refused by the RESULT guard, file untouched', () => {
    // `[tool] skills = "oops"` 能通过 validate 并正常 link;旧路径写下去会让文件不可解析,
    // 并让**别的 section** 的已声明技能从所有读取者眼里消失。枚举形状挡不住它 —— 这条护栏能。
    const src = '[deck]\nmax_cards = 10\n\n[tool]\nskills = "oops"\n\n[innate.skills.keep]\npath = "k"\n'
    const out = spliceInsertSkill(src, 'tool', 'beta', { path: 'github.com/a/b/beta' })
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('would-corrupt')
    expect(out.message).toContain('refusing to write')
  })

  it('R2-H2: the EOF insert path also uses the file\'s own line ending', () => {
    const crlf = '[deck]\r\nmax_cards = 10\r\n'
    const out = spliceInsertSkill(crlf, 'innate', 'alpha', { path: 'p' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).not.toMatch(/(?<!\r)\n/)
  })

  it('the empty-map branch is pinned (mutation `skills = {, beta = …}` must not be reachable)', () => {
    const empty = '[deck]\nmax_cards = 10\n\n[tool]\nskills = {}\n'
    const out = spliceInsertSkill(empty, 'tool', 'beta', { path: 'p' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('skills = {beta = { path = "p" }}')
    expect(() => parseTOML(out.src, { range: true })).not.toThrow()
  })
})


describe('ZK-impl round-3:R3-H1 越界剪裁(组内嵌套必须折叠)', () => {
  const SRC = `[deck]
max_cards = 10

# ── tool ──
[tool]
skills.alpha = { path = "localhost/me/alpha", source = "https://x" }

# ── combo ──
[combo.weekly]
prompt = "keep me"
`

  it('an inline-map entry with inner fields does not eat the following comment/section', () => {
    // 内层字段(path/source)的完整路径同样以 `skills.alpha.` 为前缀 → 也是命中;
    // 不折叠嵌套就先用内层偏移剪过一次,再用外层偏移剪**已缩短的字符串** → 越界吃掉后面
    const out = spliceRemoveSkill(SRC, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    // `[tool]` 表头也走 —— 该 section 空了,与对象层的级联一致(删键 → 删 section)。
    // 上方那条 `# ── tool ──` 注释**留在原地**(用户的文字,deck 没创建它)——
    // 这就是"孤注释"的既定形态,不是漏删。
    expect(out.src).toBe(`[deck]
max_cards = 10

# ── tool ──
# ── combo ──
[combo.weekly]
prompt = "keep me"
`)
  })
})


describe('ZK-impl round-4:R4-H1 内联 map 的字段条目 + 判别性测试', () => {
  const MAP2 = '[deck]\nmax_cards = 10\n\n[tool]\nskills = { alpha.path = "a", beta.path = "b" }\n'

  it('R4-H1: removing the last field of a dotted map entry keeps the file valid (no dangling comma)', () => {
    const out = spliceRemoveSkill(MAP2, 'tool', 'beta')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe('[deck]\nmax_cards = 10\n\n[tool]\nskills = { alpha.path = "a" }\n')
  })

  it('R4-H1b: removing a non-last field keeps the file valid too', () => {
    const out = spliceRemoveSkill(MAP2, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe('[deck]\nmax_cards = 10\n\n[tool]\nskills = { beta.path = "b" }\n')
  })

  it('R4-H1c: emptying the map leaves no `skills = {  }` residue', () => {
    const one = '[deck]\nmax_cards = 10\n\n[tool]\nskills = { alpha.path = "a" }\n\n[combo.weekly]\nprompt = "k"\n'
    const out = spliceRemoveSkill(one, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).not.toContain('skills =')
    expect(out.src).not.toContain('[tool]')
    expect(out.src).toContain('[combo.weekly]')
  })

  it('the adjacency gate is pinned: a comment between the empty section and the table must survive', () => {
    // 删掉 isAdjacent 判据(合并区间)会把这行注释一起吃掉 —— 这条测试就是它的判别性
    const src = '[deck]\nmax_cards = 10\n\n[tool]\n# 这段注释是用户的文字\n[tool.skills]\nalpha = { path = "x" }\n'
    const out = spliceRemoveSkill(src, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('# 这段注释是用户的文字')
    expect(out.src).not.toContain('alpha')
  })

  it('the EOF path uses the insertion point, not a scan (LF file with CRLF inside a string)', () => {
    const lf = '[deck]\nmax_cards = 10\nprompt = """\r\ninside\r\n"""\n'
    const out = spliceInsertSkill(lf, 'innate', 'alpha', { path: 'p' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    // 末尾插入的分隔符必须跟随**该处**的行尾(LF),不被字符串里的 CRLF 带偏
    expect(out.src).toMatch(/"""\n\n\[innate\.skills\.alpha\]/)
  })
})

describe('units + line endings', () => {
  it('a non-ASCII file splices at the right place (code units, not bytes)', () => {
    // 若实现把 offset 当字节用,`→` 之后的所有定位都会偏 —— 这里用"删完必须与写死的期望相同"抓它
    const out = spliceRemoveSkill(DENSE, 'tool', 'beta')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('[tool.skills.alpha]\npath = "github.com/a/b/alpha"\nrole = "调试 → 定位 → 修复"')
    expect(out.src).toContain('[combo.weekly]\nprompt = "keep"\n')
    expect(out.src).not.toContain('beta')
  })

  it('CRLF: the seam keeps exactly one blank line and no lone-CR debris', () => {
    const crlf = '[deck]\r\nmax_cards = 10\r\n\r\n[tool.skills.alpha]\r\npath = "x"\r\n\r\n[tool.skills.beta]\r\npath = "y"\r\n'
    const out = spliceRemoveSkill(crlf, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe('[deck]\r\nmax_cards = 10\r\n\r\n[tool.skills.beta]\r\npath = "y"\r\n')
    expect(out.src).not.toMatch(/\r[^\n]/)
  })
})
