#!/usr/bin/env bun
/**
 * toml-splice.test.ts — 最小影响写入:三种形状 × {删,增}(ADR-20260910152957509 §规格)
 *
 * 断言一律是**写死的期望文本**(逐字节比较),不是"原文减去那一段" ——
 * 后者是同义反复:期望值由被测代码的形状推出来,永远对(ZK review 904 round-2 指出)。
 *
 * fixture **含非 ASCII 字符**:纯 ASCII 会让"偏移单位当成字节"那类错误永远绿着骗人(H3)。
 *
 * Run: bun test packages/lythoskill-deck/src/toml-splice.test.ts
 */

import { describe, it, expect } from 'bun:test'
import { spliceRemoveSkill, spliceInsertSkill } from './toml-splice.ts'

/** 注释密集 + 非 ASCII(`→` 让 code unit ≠ 字节)的常态 deck */
const DENSE = `# Skill Deck — generated by lythoskill-deck
# 这份文件的注释是给人看的,不是给序列化器看的
[deck]
max_cards = 10           # budget
working_set = ".claude/skills"
cold_pool = "../pool"

# ── tool skills ──
[tool.skills.alpha]
path = "github.com/a/b/alpha"
role = "调试 → 定位 → 修复"

[tool.skills.beta]
path = "github.com/a/b/beta"

[combo.weekly]
prompt = "keep"
`

describe('spliceRemoveSkill — ① table 形状', () => {
  it('removes exactly that block, keeps every comment, restores the file的接缝', () => {
    const out = spliceRemoveSkill(DENSE, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`# Skill Deck — generated by lythoskill-deck
# 这份文件的注释是给人看的,不是给序列化器看的
[deck]
max_cards = 10           # budget
working_set = ".claude/skills"
cold_pool = "../pool"

# ── tool skills ──
[tool.skills.beta]
path = "github.com/a/b/beta"

[combo.weekly]
prompt = "keep"
`)
    // 非 ASCII 那一行删掉后,后面的行仍逐字节不变(单位错了就会在这里裂开)
    expect(out.src).toContain('调试 → 定位 → 修复' === '' ? '' : 'prompt = "keep"')
    expect(out.src.split('\n').filter(l => l.trimStart().startsWith('#')).length).toBe(
      DENSE.split('\n').filter(l => l.trimStart().startsWith('#')).length,
    )
  })

  it('is a no-op-safe error when the alias is not there (reports what it looked for)', () => {
    const out = spliceRemoveSkill(DENSE, 'tool', 'nope')
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('not-found')
    expect(out.message).toContain('[tool.skills.nope]')
    expect(out.message).toContain('legacy')
  })
})

describe('spliceRemoveSkill — ② [tool.skills] 内联条目', () => {
  const INLINE = `[deck]
max_cards = 10

[tool.skills]
alpha = { path = "github.com/a/b/alpha" }
beta = { path = "github.com/a/b/beta" }
`

  it('removes just that entry', () => {
    const out = spliceRemoveSkill(INLINE, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`[deck]
max_cards = 10

[tool.skills]
beta = { path = "github.com/a/b/beta" }
`)
  })

  it('cascades: the last entry gone → the [tool.skills] header goes too', () => {
    const only = `[deck]
max_cards = 10

[tool.skills]
alpha = { path = "github.com/a/b/alpha" }
`
    const out = spliceRemoveSkill(only, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    // 尾部那行空行**刻意不整理**(ADR §规格「尾部残渣」:整理 = 重写)
    expect(out.src).toBe('[deck]\nmax_cards = 10\n\n')
  })
})

describe('spliceRemoveSkill — ③ legacy 数组', () => {
  const LEGACY = `[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha", "github.com/a/b/beta" ]

[combo.weekly]
prompt = "keep"
`

  it('removes the element + its comma and does NOT reformat the rest', () => {
    const out = spliceRemoveSkill(LEGACY, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('skills = [ "github.com/a/b/beta" ]')
    expect(out.src).toContain('[combo.weekly]')
  })

  it('cascades: the last element gone → the skills key goes, then the empty section header', () => {
    const second = spliceRemoveSkill(LEGACY, 'tool', 'beta')
    expect(second.ok).toBe(true)
    if (!second.ok) return
    expect(second.src).toBe(`[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha" ]

[combo.weekly]
prompt = "keep"
`)

    const one = `[deck]
max_cards = 10

[tool]
skills = ["github.com/a/b/alpha"]

[combo.weekly]
prompt = "keep"
`
    const o2 = spliceRemoveSkill(one, 'tool', 'alpha')
    expect(o2.ok).toBe(true)
    if (!o2.ok) return
    expect(o2.src).not.toContain('skills = [')
    expect(o2.src).not.toContain('[tool]')
    expect(o2.src).toContain('[combo.weekly]')
  })
})

describe('spliceInsertSkill', () => {
  it('inserts after the last same-prefix table, one blank line, block without trailing newline', () => {
    const out = spliceInsertSkill(DENSE, 'tool', 'gamma', { path: 'github.com/a/b/gamma' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain(`[tool.skills.beta]
path = "github.com/a/b/beta"

[tool.skills.gamma]
path = "github.com/a/b/gamma"

[combo.weekly]`)
    expect(out.src.split('\n').filter(l => l.trimStart().startsWith('#')).length).toBe(
      DENSE.split('\n').filter(l => l.trimStart().startsWith('#')).length,
    )
  })

  it('carries source when given, and lands on an empty deck', () => {
    const out = spliceInsertSkill('[deck]\nmax_cards = 10\n', 'tool', 'alpha', {
      path: 'github.com/a/b/alpha',
      source: 'https://github.com/a/b/blob/HEAD/alpha/SKILL.md',
    })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`[deck]
max_cards = 10

[tool.skills.alpha]
path = "github.com/a/b/alpha"
source = "https://github.com/a/b/blob/HEAD/alpha/SKILL.md"
`)
  })

  it('legacy array + path-only + derivable alias → appends a string element, nothing else moves', () => {
    const legacy = `[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha" ]
`
    const out = spliceInsertSkill(legacy, 'tool', 'beta', { path: 'github.com/a/b/beta' })
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe(`[deck]
max_cards = 10

[tool]
skills = [ "github.com/a/b/alpha", "github.com/a/b/beta" ]
`)
  })

  it('legacy array + a source field → refuses and names deck migrate-schema', () => {
    const legacy = '[tool]\nskills = ["github.com/a/b/alpha"]\n'
    const out = spliceInsertSkill(legacy, 'tool', 'beta', {
      path: 'github.com/a/b/beta',
      source: 'https://github.com/a/b/blob/HEAD/beta/SKILL.md',
    })
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('unrepresentable')
    expect(out.message).toContain('migrate-schema')
    expect(out.message).toContain('cold pool')
    expect(out.message).toContain('github.com/a/b/beta') // 点名它看到的 locator
  })

  it('legacy array + a custom alias → refuses (alias is the key, not a field)', () => {
    const legacy = '[tool]\nskills = ["github.com/a/b/alpha"]\n'
    const out = spliceInsertSkill(legacy, 'tool', 'custom', { path: 'github.com/a/b/beta' })
    expect(out.ok).toBe(false)
    if (out.ok) return
    expect(out.code).toBe('unrepresentable')
    expect(out.message).toContain("custom alias 'custom'")
  })
})

describe('units + line endings', () => {
  it('a non-ASCII file splices at the right place (code units, not bytes)', () => {
    // 若实现把 offset 当字节用,`→` 之后的所有定位都会偏 —— 这里用"删完必须与写死的期望相同"抓它
    const out = spliceRemoveSkill(DENSE, 'tool', 'beta')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toContain('[tool.skills.alpha]\npath = "github.com/a/b/alpha"\nrole = "调试 → 定位 → 修复"')
    expect(out.src).toContain('[combo.weekly]\nprompt = "keep"\n')
    expect(out.src).not.toContain('beta')
  })

  it('CRLF: the seam keeps exactly one blank line and no lone-CR debris', () => {
    const crlf = '[deck]\r\nmax_cards = 10\r\n\r\n[tool.skills.alpha]\r\npath = "x"\r\n\r\n[tool.skills.beta]\r\npath = "y"\r\n'
    const out = spliceRemoveSkill(crlf, 'tool', 'alpha')
    expect(out.ok).toBe(true)
    if (!out.ok) return
    expect(out.src).toBe('[deck]\r\nmax_cards = 10\r\n\r\n[tool.skills.beta]\r\npath = "y"\r\n')
    expect(out.src).not.toMatch(/\r[^\n]/)
  })
})
