const fence = '`'.repeat(3)

// -- workspace root --------------------------------
export const rootPackageJson = (name: string) =>
  JSON.stringify(
    {
      name: `${name}-workspace`,
      version: '0.1.0',
      private: true,
      workspaces: ['packages/*'],
      devDependencies: { husky: '^9.1.7' },
      scripts: { prepare: 'husky' },
    },
    null,
    2
  ) + '\n'

export const pnpmWorkspace = () =>
`packages:
  - 'packages/*'
`

export const gitignore = () =>
`node_modules/
*.tsbuildinfo
.DS_Store
playground/
dist/

# Runtime config (project-local, generated by init)
.project-workflow.json

# npm access token (local-only, never commit)
.npm-access

# Private operational docs (local-only, never commit)
.private/

# Runtime lock file (contains absolute local paths, not portable)
skill-deck.lock

# Temporary directories and files
tmp/
.tmp/

# Husky internal (auto-generated)
.husky/_
`

export const skillDeckToml = (name: string) =>
`[deck]
working_set = ".claude/skills"
cold_pool   = "~/.agents/skill-repos"
max_cards   = 10

[tool]
skills = ["${name}"]
`

export const huskyPreCommit = () =>
`#!/bin/sh
# Auto-rebuild skills when source files change in packages/**/skill/

STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep '^packages/.*/skill/' || true)

if [ -n "$STAGED" ]; then
  echo "🛠️  Skill source files changed, rebuilding all skills..."
  bun packages/lythoskill-creator/src/cli.ts build --all

  # Stage built output so skills/ stays in sync with packages/**/skill/
  git add skills/
  echo "✅ Skills rebuilt and staged"
fi
`

// -- starter package --------------------------------
export const starterPackageJson = (name: string) =>
  JSON.stringify(
    {
      name,
      version: '0.1.0',
      description: 'TODO -- describe what this package does',
      license: 'MIT',
      publishConfig: { access: 'public' },
      type: 'module',
      bin: { [name]: './src/cli.ts' },
      files: ['src', 'README.md', 'LICENSE'],
    },
    null,
    2
  ) + '\n'

export const starterTsconfig = () =>
  JSON.stringify(
    {
      compilerOptions: {
        target: 'ESNext',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        types: ['bun-types'],
      },
      include: ['src/**/*'],
    },
    null,
    2
  ) + '\n'

export const starterCli = (name: string) =>
`#!/usr/bin/env bun
import { hello } from './index.js'
import pkg from '../package.json' with { type: 'json' }
const [command, ...args] = process.argv.slice(2)

switch (command) {
  case 'hello':
    console.log(hello())
    break
  case 'version':
    console.log(pkg.version)
    break
  default:
    console.log(
      '${name} -- your skill starter\\n' +
      '\\n' +
      'Commands:\\n' +
      '  hello    Say hello\\n' +
      '  version  Show version'
    )
}
`

export const starterIndex = (name: string) =>
`export function hello(): string {
  return 'Hello from ${name}!'
}
`

// -- example skill ----------------------------------
export const exampleSkillMd = (skillName: string, starterName: string) =>
`---
name: ${skillName}
version: 0.1.0
description: |
  TODO -- describe what this skill does in one sentence.
  Keep it under 120 characters.
when_to_use: |
  TODO -- list trigger phrases that tell an agent when to consider this skill.
  Example: "generate architecture diagram", "write test cases".
---

# ${skillName}

## Scripts

### run

Run the hello command.

${fence}bash
bunx ${starterName} hello
${fence}
`

export const skillScript = (starterName: string, command: string) =>
`#!/bin/bash
bunx ${starterName} ${command} "$@"
`
