import type { EntropyConfig, EntropyIO, CheckResult, CheckName } from './types.ts'

export function checkCortexProbe(config: EntropyConfig, io: EntropyIO): CheckResult {
  const cortexCli = `${config.projectDir}/packages/lythoskill-project-cortex/src/cli.ts`
  if (!io.exists(cortexCli)) {
    return { name: 'cortex-probe', status: 'skip', message: 'Cortex CLI not found' }
  }

  const result = io.exec('bun', [cortexCli, 'probe'])
  if (result.exitCode !== 0) {
    return { name: 'cortex-probe', status: 'warn', message: 'Cortex probe failed to run' }
  }

  const lines = result.stdout.split('\n')
  const warnings: string[] = []
  for (const line of lines) {
    if (line.includes('⚠️') || line.includes('📭')) {
      warnings.push(line.trim())
    }
  }

  if (warnings.length === 0) {
    return { name: 'cortex-probe', status: 'pass', message: 'Cortex clean' }
  }

  const truncated = warnings.length > 20
  return {
    name: 'cortex-probe',
    status: 'warn',
    message: `${warnings.length} item(s) from cortex probe`,
    details: [
      ...warnings.slice(0, 20),
      ...(truncated ? [`... and ${warnings.length - 20} more. Run cortex probe for full list.`] : []),
    ],
    remediation: [
      '<spawn subagent to clean up cortex governance debt>',
      '',
      'Context:',
      '- Proposed ADRs may be ready for accept/reject',
      '- Accepted ADRs may have status drift (verify they should stay accepted)',
      '- Tasks may have empty shells or wrong status (verify or clean up)',
      '- Epics may be done but not archived',
      '',
      'Goal: Bring cortex to clean state.',
      'Use cortex CLI for state transitions.',
      'Write decision-log.jsonl to playground/entropy-check/.',
    ],
  }
}

export function checkSymlinksInSkills(config: EntropyConfig, io: EntropyIO): CheckResult {
  const skillsDir = `${config.projectDir}/skills`
  if (!io.exists(skillsDir)) {
    return { name: 'symlinks-in-skills', status: 'skip', message: 'skills/ directory not found' }
  }

  const entries = io.listDir(skillsDir)
  const symlinks: string[] = []

  for (const entry of entries) {
    const fullPath = `${skillsDir}/${entry}`
    const stat = io.exec('stat', ['-c', '%F', fullPath])
    if (stat.stdout.includes('symbolic link')) {
      symlinks.push(entry)
    }
  }

  if (symlinks.length === 0) {
    return { name: 'symlinks-in-skills', status: 'pass', message: 'No symlinks in skills/' }
  }

  return {
    name: 'symlinks-in-skills',
    status: 'fail',
    message: `${symlinks.length} symlink(s) found in skills/`,
    details: symlinks,
    remediation: [
      '<spawn subagent to clean symlink pollution in skills/>',
      '',
      'Context: skills/ is build output — symlinks indicate working_set collision.',
      '',
      'Goal: Remove symlinks and rebuild skills.',
      'Write decision-log.jsonl to playground/entropy-check/.',
    ],
  }
}

export function checkWorkingSetLeaks(config: EntropyConfig, io: EntropyIO): CheckResult {
  const workingSets = [
    `${config.projectDir}/.agents/skills`,
    `${config.projectDir}/.kimi/skills`,
    `${config.projectDir}/.cursor/skills`,
    `${config.projectDir}/.codex/skills`,
  ]

  const leaks: string[] = []
  for (const ws of workingSets) {
    const result = io.exec('git', ['ls-files', ws])
    if (result.stdout.trim()) {
      leaks.push(...result.stdout.trim().split('\n').filter(Boolean))
    }
  }

  if (leaks.length === 0) {
    return { name: 'working-set-leaks', status: 'pass', message: 'No working set leaks in git' }
  }

  return {
    name: 'working-set-leaks',
    status: 'fail',
    message: `${leaks.length} working set file(s) tracked by git`,
    details: leaks.slice(0, 5),
    remediation: [
      '<spawn subagent to fix working set leaks>',
      '',
      'Context: Working sets are generated by deck link, never commit.',
      '',
      'Goal: Unstage leaked files and ensure .gitignore covers working set dirs.',
      'Write decision-log.jsonl to playground/entropy-check/.',
    ],
  }
}

export function checkEnvVarPrefix(config: EntropyConfig, io: EntropyIO): CheckResult {
  const packagesDir = `${config.projectDir}/packages`
  if (!io.exists(packagesDir)) {
    return { name: 'env-var-prefix', status: 'skip', message: 'packages/ directory not found' }
  }

  const result = io.exec('grep', [
    '-rn', 'LYTHOSKILL_',
    '--include=*.ts',
    packagesDir,
  ])

  const lines = result.exitCode === 0
    ? result.stdout.split('\n').filter(l => l.trim())
    : []

  const realLeaks = lines.filter(l => !l.includes('mirror.ts') && !l.includes('mirror.test.ts'))

  if (realLeaks.length === 0) {
    return { name: 'env-var-prefix', status: 'pass', message: 'No legacy prefix leaks' }
  }

  return {
    name: 'env-var-prefix',
    status: 'fail',
    message: `${realLeaks.length} legacy LYTHOSKILL_ prefix found`,
    details: realLeaks.slice(0, 5),
    remediation: [
      '<spawn subagent to replace legacy env var prefix>',
      '',
      'Context: LYTHOSKILL_ is deprecated; use LYTHOS_ instead.',
      'Mirror compat code (mirror.ts) is intentionally preserved.',
      '',
      'Goal: Replace LYTHOSKILL_ with LYTHOS_ in all source files.',
      'Write decision-log.jsonl to playground/entropy-check/.',
    ],
  }
}

export function checkMissingWeekly(config: EntropyConfig, io: EntropyIO): CheckResult {
  const dateResult = io.exec('date', ['+%V'])
  const yearResult = io.exec('date', ['+%Y'])

  if (dateResult.exitCode !== 0 || yearResult.exitCode !== 0) {
    return { name: 'missing-weekly', status: 'skip', message: 'Could not determine current week' }
  }

  const week = dateResult.stdout.trim()
  const year = yearResult.stdout.trim()
  const weeklyFile = `${config.projectDir}/weekly/${year}-W${week}.md`

  if (io.exists(weeklyFile)) {
    return { name: 'missing-weekly', status: 'pass', message: `Weekly exists: ${year}-W${week}.md` }
  }

  return {
    name: 'missing-weekly',
    status: 'warn',
    message: `No weekly for current week (W${week}): ${weeklyFile}`,
    remediation: [
      '<spawn subagent to generate weekly for W' + week + '>',
      '',
      'Context:',
      `- Week: ${year}-W${week}`,
      '- Source material: daily notes + git log + cortex INDEX',
      `- Reference format: ${config.projectDir}/weekly/${year}-W${String(Number(week) - 1).padStart(2, '0')}.md`,
      '',
      'Goal: Write the weekly file.',
      'Read project-scribe-weekly skill for format guidance.',
      'Distill core thread + quest DAG from source material.',
      'Write decision-log.jsonl to playground/entropy-check/.',
    ],
  }
}

export const ALL_CHECKS: Record<CheckName, (config: EntropyConfig, io: EntropyIO) => CheckResult> = {
  'cortex-probe': checkCortexProbe,
  'symlinks-in-skills': checkSymlinksInSkills,
  'working-set-leaks': checkWorkingSetLeaks,
  'env-var-prefix': checkEnvVarPrefix,
  'missing-weekly': checkMissingWeekly,
}
