import type { EntropyConfig, EntropyIO, CheckResult, CheckName } from './types.ts'

export function checkCortexProbe(config: EntropyConfig, io: EntropyIO): CheckResult {
  const cortexCli = `${config.projectDir}/packages/lythoskill-project-cortex/src/cli.ts`
  if (!io.exists(cortexCli)) {
    return { name: 'cortex-probe', status: 'skip', message: 'Cortex CLI not found' }
  }

  const result = io.exec('bun', [cortexCli, 'probe'])
  if (result.exitCode !== 0) {
    return { name: 'cortex-probe', status: 'warn', message: 'Cortex probe failed to run' }
  }

  const lines = result.stdout.split('\n')
  const warnings: string[] = []
  for (const line of lines) {
    if (line.includes('⚠️') || line.includes('📭')) {
      warnings.push(line.trim())
    }
  }

  if (warnings.length === 0) {
    return { name: 'cortex-probe', status: 'pass', message: 'Cortex clean' }
  }

  return {
    name: 'cortex-probe',
    status: 'warn',
    message: `${warnings.length} item(s) from cortex probe`,
    details: warnings.slice(0, 10),
    remediation: [
      { action: 'Review ADR status', command: 'bunx @lythos/project-cortex adr list', note: 'Accept proposed ADRs whose implementation has landed; reject abandoned ones' },
      { action: 'Clean empty-shell tasks', command: "grep -rl 'PLACEHOLDER' cortex/tasks/", note: 'Delete or fill in requirements for each found' },
      { action: 'Archive completed epics', command: 'bunx @lythos/project-cortex epic list', note: 'Move done epics to archived status' },
      { action: 'Verification', command: 'bun scripts/entropy-check/index.ts', note: 'Re-run entropy-check to confirm clean' },
    ],
  }
}

export function checkSymlinksInSkills(config: EntropyConfig, io: EntropyIO): CheckResult {
  const skillsDir = `${config.projectDir}/skills`
  if (!io.exists(skillsDir)) {
    return { name: 'symlinks-in-skills', status: 'skip', message: 'skills/ directory not found' }
  }

  const entries = io.listDir(skillsDir)
  const symlinks: string[] = []

  for (const entry of entries) {
    const fullPath = `${skillsDir}/${entry}`
    // Use exec to check if it's a symlink (L stat)
    const stat = io.exec('stat', ['-c', '%F', fullPath])
    if (stat.stdout.includes('symbolic link')) {
      symlinks.push(entry)
    }
  }

  if (symlinks.length === 0) {
    return { name: 'symlinks-in-skills', status: 'pass', message: 'No symlinks in skills/' }
  }

  return {
    name: 'symlinks-in-skills',
    status: 'fail',
    message: `${symlinks.length} symlink(s) found in skills/`,
    details: symlinks,
    remediation: [
      { action: 'Remove symlinks from build output', command: `rm ${symlinks.map(s => `skills/${s}`).join(' ')}`, note: 'skills/ is build output — symlinks indicate working_set collision' },
      { action: 'Rebuild all skills', command: 'bunx @lythos/skill-creator build --all' },
      { action: 'Verification', command: 'find skills/ -maxdepth 1 -type l | wc -l', note: 'Should output 0' },
    ],
  }
}

export function checkWorkingSetLeaks(config: EntropyConfig, io: EntropyIO): CheckResult {
  const workingSets = [
    `${config.projectDir}/.agents/skills`,
    `${config.projectDir}/.kimi/skills`,
    `${config.projectDir}/.cursor/skills`,
    `${config.projectDir}/.codex/skills`,
  ]

  const leaks: string[] = []
  for (const ws of workingSets) {
    const result = io.exec('git', ['ls-files', ws])
    if (result.stdout.trim()) {
      leaks.push(...result.stdout.trim().split('\n').filter(Boolean))
    }
  }

  if (leaks.length === 0) {
    return { name: 'working-set-leaks', status: 'pass', message: 'No working set leaks in git' }
  }

  return {
    name: 'working-set-leaks',
    status: 'fail',
    message: `${leaks.length} working set file(s) tracked by git`,
    details: leaks.slice(0, 5),
    remediation: [
      { action: 'Unstage leaked working set files', command: `git rm --cached ${leaks.slice(0, 3).join(' ')}${leaks.length > 3 ? ' ...' : ''}`, note: 'Working sets are generated by deck link, never commit' },
      { action: 'Verify .gitignore', command: "grep -E '^\\.agents/skills/' .gitignore", note: 'Ensure working set dirs are gitignored' },
      { action: 'Verification', command: 'git ls-files .agents/skills/ .kimi/skills/ .cursor/skills/ .codex/skills/ | head -5', note: 'Should output nothing' },
    ],
  }
}

export function checkEnvVarPrefix(config: EntropyConfig, io: EntropyIO): CheckResult {
  const packagesDir = `${config.projectDir}/packages`
  if (!io.exists(packagesDir)) {
    return { name: 'env-var-prefix', status: 'skip', message: 'packages/ directory not found' }
  }

  const result = io.exec('grep', [
    '-rn', 'LYTHOSKILL_',
    '--include=*.ts',
    packagesDir,
  ])

  // grep exits 1 when no matches — that's "pass" for this check
  const lines = result.exitCode === 0
    ? result.stdout.split('\n').filter(l => l.trim())
    : []

  // Filter out mirror compat code
  const realLeaks = lines.filter(l => !l.includes('mirror.ts') && !l.includes('mirror.test.ts'))

  if (realLeaks.length === 0) {
    return { name: 'env-var-prefix', status: 'pass', message: 'No legacy prefix leaks' }
  }

  return {
    name: 'env-var-prefix',
    status: 'fail',
    message: `${realLeaks.length} legacy LYTHOSKILL_ prefix found`,
    details: realLeaks.slice(0, 5),
    remediation: [
      { action: 'Review occurrences', command: "grep -rn 'LYTHOSKILL_' --include='*.ts' packages/ | grep -v mirror", note: 'mirror.ts compat code is intentionally preserved' },
      { action: 'Replace with LYTHOS_ prefix', command: '# Edit each file: sed -i "" or manual replace', note: 'LYTHOSKILL_GH_MIRROR → LYTHOS_GH_MIRROR, etc.' },
      { action: 'Verification', command: 'bun scripts/entropy-check/index.ts', note: 'Re-run to confirm env-var-prefix passes' },
    ],
  }
}

export function checkMissingWeekly(config: EntropyConfig, io: EntropyIO): CheckResult {
  const dateResult = io.exec('date', ['+%V'])
  const yearResult = io.exec('date', ['+%Y'])

  if (dateResult.exitCode !== 0 || yearResult.exitCode !== 0) {
    return { name: 'missing-weekly', status: 'skip', message: 'Could not determine current week' }
  }

  const week = dateResult.stdout.trim()
  const year = yearResult.stdout.trim()
  const weeklyFile = `${config.projectDir}/weekly/${year}-W${week}.md`

  if (io.exists(weeklyFile)) {
    return { name: 'missing-weekly', status: 'pass', message: `Weekly exists: ${year}-W${week}.md` }
  }

  return {
    name: 'missing-weekly',
    status: 'warn',
    message: `No weekly for current week (W${week}): ${weeklyFile}`,
    remediation: [
      { action: 'Collect material', command: `ls daily/${year}-*.md; git log --since="${year}-W${week} start" --oneline`, note: 'Gather daily notes and git activity for the week' },
      { action: 'Generate weekly', command: '# Read /lythoskill-project-scribe-weekly skill', note: 'Distill core thread + quest DAG into frontmatter-rich weekly doc' },
      { action: 'Write weekly file', command: `weekly/${year}-W${week}.md`, note: 'See weekly/2026-W20.md for format reference' },
      { action: 'Verification', command: `ls ${weeklyFile}`, note: 'Should exist' },
    ],
  }
}

export const ALL_CHECKS: Record<CheckName, (config: EntropyConfig, io: EntropyIO) => CheckResult> = {
  'cortex-probe': checkCortexProbe,
  'symlinks-in-skills': checkSymlinksInSkills,
  'working-set-leaks': checkWorkingSetLeaks,
  'env-var-prefix': checkEnvVarPrefix,
  'missing-weekly': checkMissingWeekly,
}
